library(devtools)
library(data.table)
library(ggplot2)
library(base64enc)
library(yaml)
library(dplyr)
library(caret)
library(stringr)
library(tidyr)
library(arrow)
library(purrr)
library(stats)
library(gridExtra)


# ------------------------
# Local environments
# ------------------------
data_sample_env <- new.env()
data_utils_env <- new.env()
data_input_env <- new.env()
data_output_env <- new.env()
vis_env <- new.env()
model_linear_env <- new.env()
model_wrapper_env <- new.env()
model_utils_env <- new.env()
model_ruf_env <- new.env()
dmm_env <- new.env()
person_env <- new.env()
mortality_env <- new.env()
employment_env <- new.env()
model_heckman_wage_env <- new.env()